.TH yMAP· 9 2013-jan "linux" "user interface behavior guarantees"

.SH NAME
.B yMAP
- vikeys location and map-mode management

.SH PATRON
.B theseus-archegos (founder)
great greek hero and early king of athens

.SH IMAGERY
young, handsome, vigorous man armed only with sword and sandals

.SH SUMMARY
yMAP is a custom c library providing universal vikeys movement and location
management for the map-mode -- including five-dimensional navigation in x-axis, 
y-axis, z-axis, buffers, and time.

.SH SERIOUS DISCLAIMER
i'm a crazy, naive, dog-fooding c programmer.  i'm NOT trying to be best.
i optimize for learning, transparency, and ease of maintenance.  if i wanted
awesome, fast, and cutting-edge, i'd use yours ;)

.SH DOCUMENTATION FILES (see also)
.nf  
yMAP·(3)           interfacing applications with library
yMAP·(5)           user files, data streams, and configuration
yMAP·(6)           interactive feel, usage, and navigation
yMAP·(7)           decision rationale, scope, and objectives
.B yMAP·(9)···········user interface behavior guarantees

.SH FILE PURPOSE
efficient usage and reliable automation both require very predictable user
interface behaviors.  this file typically only expands on section (6) where
additional explanation is useful or required.

.SH VISUAL SELECTION
.SS selecting
during visual selection, all movement keys work exactly the same as in
map mode.  a few additional options are available, but none of them change
the cursor position.

.SS clearing
when selection is cleared, cursor always remains in last current position.
while it could be intuitive and useful for the cursor to go back to the root
or beginning, it would mean context is required to know which.  consistency is
conducive to automation.
